name: PinkedIn

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.3

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Build
      run: |
        apt-get -y update
        apt-get -y upgrade
        apt-get install -y libsqlite3-dev
        gem install bundler
        NODE_ENV=test bundle exec rails webpacker:compile
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: run rspec
      run: |
        bundle exec rspec
